baseURL = "https://martinsitar.com"
title = "Martin Sitar"
author = "Martin Sitar"
languageCode = "en-us"
enableRobotsTXT = true
disableKinds = ["taxonomy","taxonomyTerm"]
googleAnalytics = 'G-HSYQR3E229'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "work"
    name = "Work"
    url = "/work/"
    weight = 2

[params]
  custom_css = ["css/custom.css"]
  twitter_cards = true
  images = ["img/thumbnail.png"]
